DROP DATABASE IF EXISTS fullstacks;
CREATE DATABASE fullstacks;
USE fullstacks;

CREATE TABLE users (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL
);

CREATE TABLE posts (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    author INTEGER UNSIGNED NOT NULL,
    CONSTRAINT fk_author FOREIGN KEY (author) REFERENCES users(id) ON DELETE CASCADE,
    body VARCHAR(200) NOT NULL
);

